# 3.14-alpine
FROM python@sha256:faee120f7885a06fcc9677922331391fa690d911c020abb9e8025ff3d908e510
COPY tests/standalone/simulator/simulator.py /simulator.py
CMD ["python3", "-u", "/simulator.py"]
