# 3.14-alpine
FROM python:3.14-alpine@sha256:6f873e340e6786787a632c919ecfb1d2301eb33ccfbe9f0d0add16cbc0892116
COPY tests/standalone/simulator/simulator.py /simulator.py
CMD ["python3", "-u", "/simulator.py"]
