# 3.14-alpine
FROM python:3.14-alpine@sha256:6f873e340e6786787a632c919ecfb1d2301eb33ccfbe9f0d0add16cbc0892116
WORKDIR /
COPY pyproject.toml uv.lock /tmp/uv/
COPY rootfs /
# 0.11.2
COPY --from=ghcr.io/astral-sh/uv@sha256:b1e699368d24c57cda93c338a57a8c5a119009ba809305cc8e86986d4a006754 /uv /uvx /bin/
RUN --mount=type=cache,target=/root/.cache/uv \
    cd /tmp/uv && uv export --frozen --no-dev --no-emit-project --no-hashes | \
    uv pip install --system --no-cache -r - && \
    cd / && rm -rf /tmp/uv
# Bake in the test configuration
COPY tests/standalone/config/options.json /data/options.json
CMD [ "python3", "/usr/src/s0pcm_reader.py" ]
