# 3.14-alpine
FROM python:3.14-alpine@sha256:01f125438100bb6b5770c0b1349e5200b23ca0ae20a976b5bd8628457af607ae
WORKDIR /
COPY pyproject.toml uv.lock /tmp/uv/
COPY rootfs /
# 0.11.2
COPY --from=ghcr.io/astral-sh/uv@sha256:240fb85ab0f263ef12f492d8476aa3a2e4e1e333f7d67fbdd923d00a506a516a /uv /uvx /bin/
RUN --mount=type=cache,target=/root/.cache/uv \
    cd /tmp/uv && uv export --frozen --no-dev --no-emit-project --no-hashes | \
    uv pip install --system --no-cache -r - && \
    cd / && rm -rf /tmp/uv
# Bake in the test configuration
COPY tests/standalone/config/options.json /data/options.json
CMD [ "python3", "/usr/src/s0pcm_reader.py" ]
